name: all_social_downloader
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  path_provider: ^2.0.15
  video_player: ^2.4.7
  video_thumbnail: ^0.5.3
  # For media scanning
  
  permission_handler: ^12.0.0
  flutter_local_notifications: ^14.1.5
  shared_preferences: ^2.1.2
  device_info_plus: ^9.0.3
  dio: ^5.2.0
  path: ^1.8.3
  url_launcher: ^6.1.11
  share_plus: ^7.0.2
  firebase_core: ^3.13.0
  # Update win32 to a more recent version
  win32: ^5.0.0  # Using a newer version
  
  # If you're using collection, ensure it's included
  collection: ^1.17.0  # Include collection for UnmodifiableUint8ListView
  http: ^1.3.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/