// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnAw1DzsJM1wKVCEJtmnzjUH9ymjEp35M',
    appId: '1:304792745260:web:4cf54ae2d847b0c7d8a889',
    messagingSenderId: '304792745260',
    projectId: 'social-downloader-2d02b',
    authDomain: 'social-downloader-2d02b.firebaseapp.com',
    storageBucket: 'social-downloader-2d02b.firebasestorage.app',
    measurementId: 'G-Z6R4MK84ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh6CwgO1BCtkwVQHjbc4nUCGIMCDHbRrs',
    appId: '1:304792745260:android:c862df45e9fc2f81d8a889',
    messagingSenderId: '304792745260',
    projectId: 'social-downloader-2d02b',
    storageBucket: 'social-downloader-2d02b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjDsVwgupzNZNwsZxOX_bnqfg7rCsPNBs',
    appId: '1:304792745260:ios:6978eecb08062e9bd8a889',
    messagingSenderId: '304792745260',
    projectId: 'social-downloader-2d02b',
    storageBucket: 'social-downloader-2d02b.firebasestorage.app',
    iosBundleId: 'com.example.allSocialDownloader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjDsVwgupzNZNwsZxOX_bnqfg7rCsPNBs',
    appId: '1:304792745260:ios:6978eecb08062e9bd8a889',
    messagingSenderId: '304792745260',
    projectId: 'social-downloader-2d02b',
    storageBucket: 'social-downloader-2d02b.firebasestorage.app',
    iosBundleId: 'com.example.allSocialDownloader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnAw1DzsJM1wKVCEJtmnzjUH9ymjEp35M',
    appId: '1:304792745260:web:2e62116661a20f4dd8a889',
    messagingSenderId: '304792745260',
    projectId: 'social-downloader-2d02b',
    authDomain: 'social-downloader-2d02b.firebaseapp.com',
    storageBucket: 'social-downloader-2d02b.firebasestorage.app',
    measurementId: 'G-1ZNW0MZCHW',
  );
}
